### PR TITLE
[WIP] 56 improve player rankings

### PR DESCRIPTION
**Pull request by mtgmagicalhack**
@czarandy @OdinFK 

Just to let you know what I'm currently working at. 

I'm using react-virtualized to create a spreadsheet like table with a fixed header and and fixed first column. 

This is based on their scroll sync demo. 
https://bvaughn.github.io/react-virtualized/

out

Code is still very messy, but I appreciate any feedback regarding interaction etc. 

This was painful to setup (at least for me). 

Let me know, if you guys like the general direction and weather I should pursue the issue further.

### CODE REVIEW

**Comment by czarandy** [comment]
My only concern is that this prevents searching within the browser. Do you think that's an issue?

**Comment by czarandy** [comment]
If you want to send the 'watch' stuff as a separate PR we can do that right away.

**Comment by czarandy** [comment]
I guess the main advantage of infinite scroll is we don't need to have an artificial limit of top 100. So I think this is good to do just based on that.

**Comment by mtgmagicalhack** [comment]
I'm going to cherry pick the watch stuff in another PR. 

As for virtualized scrolling I think the overall direction is good, but it adds another layer of complexity. 

> My only concern is that this prevents searching within the browser. Do you think that's an issue?
Valid point and the same issue on the wizards standings page. We'd probably need to add a filter function then. 

> guess the main advantage of infinite scroll is we don't need to have an artificial limit of top 100. So I think this is good to do just based on that.

The current state has performance problems with the fixed columns. Meaning there is a noticeable delay between the native scroll and the synchronized one. I investigated, but there seems to be no easy fix. https://github.com/bvaughn/react-virtualized/issues/291 

All I wanted to do is make the first 2 columns and the header row fixed at mobile, now I'm deep down the rabbit hole. :)

Fixed data table doesn't have the performance issue, see http://facebook.github.io/fixed-data-table/example-object-data.html. But it's current state of maintenance seems bad. What do you suggest?

**Comment by mtgmagicalhack** [comment]
If we don't fix the left columns, scroll performance is top-notch, except for the header cells. I could probably style the placeholders as well, so we don't have that much flash of white space. 

out

**Comment by czarandy** [comment]
Seems pretty good. I don't think the scrolling needs to be perfect. I do think a way of jumping to specific players is important though.

**Pull request closed without merging**
