### PR TITLE
Feature/1 work

### PR DESCRIPTION
**Pull request by OdinFK**
*129-192th place for ny98
*worlds 08&09 pro points/Prizes
*name fixes

### CODE REVIEW

**Comment by czarandy** [comment]
It looks like you deleted data/pro-tour-paris-2011.json. Was that intentional?

**Comment by OdinFK** [comment]
Nope, certainly not.

**Comment by OdinFK** [comment]
With these updates finishes a big part of the editing process. All PTs are fully there, and all PTs have correct Pro Points and prizes. Also a very large part of the player names has been corrected or merged.

So, time to upload this all to server.

(Note: I restored PT Paris in the second part of this pull request)

**Comment by czarandy** [comment]
Ok, great. I merged your changes and pushed them to the site. :)

**Comment by OdinFK** [comment]
Hm. I cannot see anything. Sorry for being impatient, but the last ten days were quite the grind... :D

**Comment by czarandy** [comment]
Sorry, it should be up now

**Comment by OdinFK** [comment]
Thanks!!

**Pull request merged**
